language: node_js

node_js:
  - '0.10'

before_script:
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate < test/coverage/**/lcov.info

notifications:
  # publish build status to IRC channel: #stddev
  irc:
    channels:
    - chat.freenode.net#stddev
    on_success: always
    on_failure: always
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
  # publish build status to gitter chat room: https://gitter.im/daniellmb/stddev
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/61c5ca4c8130efdb59d8
    on_success: always
    on_failure: always
    on_start: false

env:
  - CODECLIMATE_REPO_TOKEN=0b8adcc8e05c01e61f65ea7f4176392a16cca8c18c2ce1ceea03b51512e64544